In [1]:
from getpass import getpass
import pandas as pd
from sqlalchemy import create_engine

# 1. Input password secara aman (akan muncul kolom input rahasia saat dijalankan)
db_password = getpass("Masukkan Password PostgreSQL Anda: ")

# 2. Masukkan variabel password ke dalam string koneksi (F-String)
engine = create_engine(
    f"postgresql+psycopg2://postgres:{db_password}@localhost:5432/olist_ops"
)

# 3. Jalankan query seperti biasa
df = pd.read_sql("SELECT * FROM analytics.fact_order_delivery", engine)
print("Baris terbaca:", len(df))

Baris terbaca: 96470

In [5]:
# == False: hanya ambil yang benar-benar false, baris NULL ikut tersaring keluar
# (meniru persis perilaku "NOT has_sequence_anomaly" di SQL)
d = df[df.in_analysis_period & (df.has_sequence_anomaly == False)].copy()

print("Dalam periode          :", df.in_analysis_period.sum())
print("Basis analisis (bersih):", len(d))

# 96203 & 96183

Dalam periode          : 96203
Basis analisis (bersih): 96184

In [6]:
# basis analisis (bersih) selisih 1 baris, harusnya 96183

print(df.has_sequence_anomaly.value_counts(dropna=False))
print()
print(df[df.has_sequence_anomaly.isna()][["order_id", "in_analysis_period", "carrier_ts"]])

has_sequence_anomaly
False    96447
True        23
Name: count, dtype: int64

Empty DataFrame
Columns: [order_id, in_analysis_period, carrier_ts]
Index: []

In [7]:
# Ternyata tidak ada NULL sama sekali — 96.447 False + 23 True = 96.470. Jadi keterangan error yang kamu dapat sebelumnya keliru soal NULL.

print("basis :", len(d))
print("telat :", int(d.is_late.sum()))
print("tepat :", int((~d.is_late).sum()))
print()
print(df[df.in_analysis_period].has_sequence_anomaly.value_counts())

basis : 96184
telat : 7822
tepat : 88362

has_sequence_anomaly
False    96184
True        19
Name: count, dtype: int64

In [28]:
# Melakukan pengecekan ke PostgreSQL

# SELECT COUNT(*)                        AS basis,
#        COUNT(*) FILTER (WHERE is_late) AS telat,
#        COUNT(*) FILTER (WHERE NOT is_late) AS tepat
# FROM analytics.fact_order_delivery
# WHERE in_analysis_period
#   AND NOT has_sequence_anomaly;

In [29]:
# Basis analisis (bersih): 96184 - sudah diverifikasi cocok dengan SQL

In [8]:
p = df[df.in_analysis_period]

q1 = {
    "total_pesanan"    : len(p),
    "persen_telat"     : round(p.is_late.mean() * 100, 2),
    "rata2_hari_telat" : round(p[p.is_late].delay_days.mean(), 2),
    "median_lead_time" : round(p.lead_time_days.median(), 2),
}
q1

{'total_pesanan': 96203,
 'persen_telat': np.float64(8.13),
 'rata2_hari_telat': np.float64(9.55),
 'median_lead_time': np.float64(10.21)}

In [10]:
q2 = d.groupby("is_late").agg(
    jumlah       = ("order_id", "size"),
    med_ke_kurir = ("handover_days", "median"),
    med_transit  = ("transit_days", "median"),
    med_total    = ("lead_time_days", "median"),
).round(2)
q2

         jumlah  med_ke_kurir  med_transit  med_total
is_late
False     88362          2.13         6.93       9.71
True       7822          3.43        23.93      29.15

In [12]:
r = d[d.review_score.notna()]

q5 = r.groupby("is_late").agg(
    jumlah     = ("order_id", "size"),
    skor_rata2 = ("review_score", "mean"),
    persen_1_2 = ("review_score", lambda s: (s <= 2).mean() * 100),
).round(2)
q5

         jumlah  skor_rata2  persen_1_2
is_late
False     87883        4.30        9.19
True       7658        2.57       54.05

In [13]:
hasil_sql = {
    "Total pesanan"        : 96203,
    "Persen telat"         : 8.13,
    "Rata2 hari telat"     : 9.55,
    "Median lead time"     : 10.21,
    "Median transit telat" : 23.93,
    "Skor ulasan telat"    : 2.57,
}
hasil_py = {
    "Total pesanan"        : len(p),
    "Persen telat"         : round(p.is_late.mean() * 100, 2),
    "Rata2 hari telat"     : round(p[p.is_late].delay_days.mean(), 2),
    "Median lead time"     : round(p.lead_time_days.median(), 2),
    "Median transit telat" : round(d[d.is_late].transit_days.median(), 2),
    "Skor ulasan telat"    : round(r[r.is_late].review_score.mean(), 2),
}

banding = pd.DataFrame({"SQL": hasil_sql, "Python": hasil_py})
banding["cocok"] = banding.SQL == banding.Python
banding

                           SQL    Python  cocok
Total pesanan         96203.00  96203.00   True
Persen telat              8.13      8.13   True
Rata2 hari telat          9.55      9.55   True
Median lead time         10.21     10.21   True
Median transit telat     23.93     23.93   True
Skor ulasan telat         2.57      2.57   True

In [34]:
# kolom = ["order_id", "customer_state", "purchase_ts", "delivered_ts", "estimated_ts",
#          "lead_time_days", "handover_days", "transit_days", "delay_days",
#          "is_late", "review_score", "order_value"]

# d[kolom].to_csv(
#     r"C:\Users\msibr\OneDrive\Data Analyst\10. Portofolio\Project 1\04_excel\fact_delivery.csv",
#     index=False
# )

# print("Tersimpan. Baris:", len(d))

In [35]:
# Format region laptop pakai Indonesia, setting excel mengikuti Format Indonesia

In [15]:
# Ekspor ulang csv dengan menyesuaikan Format Indonesia

kolom = ["order_id", "customer_state", "purchase_ts", "delivered_ts", "estimated_ts",
         "lead_time_days", "handover_days", "transit_days", "delay_days",
         "is_late", "review_score", "order_value"]

d[kolom].to_csv(
    r"C:\Users\msibr\OneDrive\Data Analyst\10. Portofolio\Project 1\04_excel\fact_delivery.csv",
    index=False,
    sep=";",
    decimal=","
)

print("Tersimpan ulang. Baris:", len(d))

OSError: Cannot save file into a non-existent directory: 'C:\Users\msibr\OneDrive\Data Analyst\10. Portofolio\Project 1\04_excel'